### ISSUE TITLE
Put quill in <Card>

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#34]
consistent border design

**Comment by frogg** [comment]
Problem: my `'./ReactQuill.css';` is not applied to the component

it should remove the border once it is applied:

```css
.quill-editor .ql-toolbar.ql-snow,
.quill-editor .ql-container.ql-snow {
  border: none;
}
```
